# 04 数据操作+数据预处理

## 常规矩阵操作 tensor

### 创建张量


In [10]:
import torch # type: ignore
x = torch.arange(12) # tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
z = torch.zeros(12) # 全是0,形状为(12)
o = torch.ones(2,3,4) # 全是1,形状为(2,3,4)
r = torch.randn(3, 4) # 创建一个形状为（3,4）的张量。 其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。
t = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) # 直接创建
x, z, o, r, t

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[-1.4397, -0.1033, -1.1628,  1.5154],
         [-1.6699,  1.1434,  1.6220, -0.8131],
         [-0.5327,  0.9932,  0.5888, -1.4618]]),
 tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]))

### 创建张量(续)

In [11]:
# torch.normal: 指定平均值、标准差、形状
n = torch.normal(0, 1, size=(3, 4))
n

tensor([[-0.7203, -1.1268,  0.8621, -1.9318],
        [-2.8751,  0.8117,  0.2940, -0.0852],
        [-0.8551,  0.8527,  1.5955, -0.1183]])

### 张量的属性

In [12]:
shape = x.shape # x的形状(维数,每维的长度) ，这里torch.Size([12])
numel = x.numel() # 张量中元素总数,这里为12
shape, numel

(torch.Size([12]), 12)


### 张量操作

+ reshape：改变张量形状

In [13]:
x2 = x.reshape(3,2,2) # 改变张量形状, 三个数必须满足乘积和元素总数一样
x2

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

+ sum：元素求和

In [14]:
s = x.sum()
s

tensor(66)

可以按轴求和：按哪个维度求和，哪个维度就没了

In [15]:
s_x = x2.sum(axis=0)
s_x

tensor([[12, 15],
        [18, 21]])

### 运算符

按每个元素分别计算：



In [16]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([2,2,2,2])
plus = x + y # tensor([3,4,5,6])
minus = x - y # tensor([-1,0,1,2])
exp = torch.exp(x) # 计算每个元素的e指数
equal = x == y # 结果是每个位置元素的相等情况
plus, minus, exp, equal

(tensor([3, 4, 5, 6]),
 tensor([-1,  0,  1,  2]),
 tensor([ 2.7183,  7.3891, 20.0855, 54.5981]),
 tensor([False,  True, False, False]))

等等


### 广播机制

当两个矩阵维数不一致时，会触发广播机制

In [17]:
a = torch.arange(3).reshape((3, 1)) # [[0],[1],[2]]^T
b = torch.arange(2).reshape((1, 2)) # [[0],[1]]
a + b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 索引和切片

各维度之间由逗号分隔

In [18]:
a = torch.arange(12).reshape(3,4)
a[1,2] # 访问一个元素
a[0:1,1:4] # 访问一个区域
a[::2,::2] # 带有步长

# 也可以给一片区域/一个位置赋值:
a[:,0:2] = 12 # 给所有行的0-1列赋值12
a

tensor([[12, 12,  2,  3],
        [12, 12,  6,  7],
        [12, 12, 10, 11]])